server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.aj.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #集群版
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
      instance-id: payment8001
      prefer-ip-address: true
      #客户端向服务端发送心跳的时间间隔，默认是30秒，单位为秒
      #lease-renewal-interval-in-seconds: 30
      #Eureka服务端在收到最后一次心跳后等待时间上限,单位为秒,默认90秒,超时剔除服务
      #lease-expiration-duration-in-seconds: 90