server:
  port: 8001


spring:
  application:
    name: cloud-provider-hystrix-payment


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #集群版
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka
 # instance:
  #    instance-id: payment8001
  #    prefer-ip-address: true
      #客户端向服务端发送心跳的时间间隔，默认是30秒，单位为秒
      #lease-renewal-interval-in-seconds: 30
      #Eureka服务端在收到最后一次心跳后等待时间上限,单位为秒,默认90秒,超时剔除服务
      #lease-expiration-duration-in-seconds: 90